# Информация о базе данных BattlePass (InCubePass)
BPdatabase:
  host: ""
  port: 3306
  database: ""
  username: ""
  password: ""
  # Название таблицы. Не путать с названием базы данных!
  table: ""
  # Использовать SSL соединение?
  useSSL: false
  # Переподключаться к базе данных при потере соединения?
  autoReconnect: true